import { RouterView, type RouteRecordRaw } from 'vue-router'
import AcademyDashboardView from '../views/AcademyDashboardView.vue'
import AchievementEntryView from '../views/AchievementEntryView.vue'
import AchievementReviewView from '../views/AchievementReviewView.vue'
import AchievementClaimView from '../views/personal-center/AchievementClaimView.vue'
import DashboardView from '../views/DashboardView.vue'
import ProjectGuideManagementView from '../views/ProjectGuideManagementView.vue'
import ProjectRecommendationView from '../views/ProjectRecommendationView.vue'
import TeacherManagementView from '../views/TeacherManagementView.vue'
import TeacherProfileEditorView from '../views/TeacherProfileEditorView.vue'

const buildModuleRoute = (route: RouteRecordRaw): RouteRecordRaw => route

export const workspaceChildrenRoutes: RouteRecordRaw[] = [
  buildModuleRoute({
    path: 'profile-editor',
    component: RouterView,
    meta: {
      title: '个人中心',
      icon: 'User',
      order: 10,
      moduleKey: 'personal-center',
      moduleRoot: true,
      requiresAuth: true,
      menuRoles: ['teacher', 'admin', 'college_admin'],
    },
    children: [
      {
        path: '',
        name: 'teacher-profile-editor',
        component: TeacherProfileEditorView,
        props: { sectionMode: 'public-profile' },
        meta: {
          title: '公开资料',
          order: 10,
          moduleKey: 'personal-center',
          requiresAuth: true,
          menuRoles: ['teacher', 'admin', 'college_admin'],
        },
      },
      {
        path: 'public-profile',
        name: 'teacher-profile-editor-public-profile',
        redirect: '/profile-editor',
        meta: {
          hiddenInMenu: true,
          order: 15,
          moduleKey: 'personal-center',
          requiresAuth: true,
          menuRoles: ['teacher', 'admin', 'college_admin'],
        },
      },
      {
        path: 'security',
        name: 'teacher-profile-editor-security',
        component: TeacherProfileEditorView,
        props: { sectionMode: 'security' },
        meta: {
          title: '账户安全',
          order: 20,
          moduleKey: 'personal-center',
          requiresAuth: true,
          menuRoles: ['teacher', 'admin', 'college_admin'],
        },
      },
      {
        path: 'achievement-entry',
        name: 'teacher-profile-editor-achievement-entry',
        component: AchievementEntryView,
        props: { sectionMode: 'manage' },
        meta: {
          title: '成果录入',
          order: 30,
          moduleKey: 'personal-center',
          requiresAuth: true,
          menuRoles: ['teacher'],
        },
      },
      {
        path: 'achievement-claims',
        name: 'teacher-profile-editor-achievement-claims',
        component: AchievementClaimView,
        meta: {
          title: '成果认领',
          order: 35,
          moduleKey: 'personal-center',
          requiresAuth: true,
          menuRoles: ['teacher'],
        },
      },
      {
        path: 'quick-links',
        name: 'teacher-profile-editor-quick-links',
        redirect: '/profile-editor',
        meta: {
          hiddenInMenu: true,
          order: 40,
          moduleKey: 'personal-center',
          requiresAuth: true,
          menuRoles: ['teacher', 'college_admin'],
        },
      },
    ],
  }),
  buildModuleRoute({
    path: 'dashboard',
    component: RouterView,
    meta: {
      title: '教师画像',
      icon: 'Odometer',
      order: 20,
      moduleKey: 'portrait',
      moduleRoot: true,
      requiresAuth: true,
      menuRoles: ['teacher'],
    },
    children: [
      {
        path: '',
        name: 'dashboard',
        component: DashboardView,
        props: { sectionMode: 'overview' },
        meta: {
          title: '能力画像',
          order: 10,
          moduleKey: 'portrait',
          requiresAuth: true,
        },
      },
      {
        path: 'dimensions',
        name: 'dashboard-dimensions',
        redirect: '/dashboard',
        meta: {
          hiddenInMenu: true,
          order: 20,
          moduleKey: 'portrait',
          requiresAuth: true,
        },
      },
      {
        path: 'trends',
        name: 'dashboard-trends',
        component: DashboardView,
        props: { sectionMode: 'trends' },
        meta: {
          title: '趋势分析',
          order: 30,
          moduleKey: 'portrait',
          requiresAuth: true,
        },
      },
      {
        path: 'keywords',
        name: 'dashboard-keywords',
        redirect: '/dashboard/trends',
        meta: {
          hiddenInMenu: true,
          order: 40,
          moduleKey: 'portrait',
          requiresAuth: true,
        },
      },
      {
        path: 'social',
        name: 'dashboard-social',
        component: DashboardView,
        props: { sectionMode: 'social' },
        meta: {
          title: '学术社交',
          order: 50,
          moduleKey: 'portrait',
          requiresAuth: true,
        },
      },
      {
        path: 'representative-achievements',
        name: 'dashboard-representative-achievements',
        component: DashboardView,
        props: { sectionMode: 'representative' },
        meta: {
          title: '全部成果',
          order: 60,
          moduleKey: 'portrait',
          requiresAuth: true,
        },
      },
    ],
  }),
  {
    path: 'profile/:id',
    name: 'profile',
    component: DashboardView,
    props: route => ({
      userId: Number(route.params.id),
      sectionMode: 'overview',
    }),
    meta: {
      title: '教师画像详情',
      icon: 'Odometer',
      order: 21,
      moduleKey: 'portrait',
      hiddenInMenu: true,
      activeMenu: '/dashboard',
      requiresAuth: true,
    },
  },
  buildModuleRoute({
    path: 'entry',
    component: RouterView,
    meta: {
      title: '成果中心',
      icon: 'Histogram',
      order: 30,
      moduleKey: 'achievement',
      moduleRoot: true,
      hiddenInMenu: true,
      requiresAuth: true,
      menuRoles: ['teacher', 'college_admin'],
    },
    children: [
      {
        path: '',
        name: 'AchievementEntry',
        component: AchievementEntryView,
        props: { sectionMode: 'overview' },
        meta: {
          title: '成果总览',
          order: 10,
          moduleKey: 'achievement',
          requiresAuth: true,
          menuRoles: ['teacher', 'college_admin'],
        },
      },
      {
        path: 'manage',
        name: 'achievement-entry-manage',
        component: AchievementEntryView,
        props: { sectionMode: 'manage' },
        meta: {
          title: '成果列表 / 录入',
          order: 20,
          moduleKey: 'achievement',
          requiresAuth: true,
          menuRoles: ['teacher', 'college_admin'],
        },
      },
      {
        path: 'import',
        name: 'achievement-entry-import',
        component: AchievementEntryView,
        props: { sectionMode: 'import' },
        meta: {
          title: 'BibTeX 导入',
          order: 30,
          moduleKey: 'achievement',
          requiresAuth: true,
          menuRoles: ['teacher', 'college_admin'],
        },
      },
      {
        path: 'statistics',
        name: 'achievement-entry-statistics',
        component: AchievementEntryView,
        props: { sectionMode: 'statistics' },
        meta: {
          title: '统计摘要',
          order: 40,
          moduleKey: 'achievement',
          requiresAuth: true,
          menuRoles: ['teacher', 'college_admin'],
        },
      },
      {
        path: 'representative',
        name: 'achievement-entry-representative',
        component: AchievementEntryView,
        props: { sectionMode: 'representative' },
        meta: {
          title: '代表成果',
          order: 50,
          moduleKey: 'achievement',
          requiresAuth: true,
          menuRoles: ['teacher', 'college_admin'],
        },
      },
    ],
  }),
  buildModuleRoute({
    path: 'graph',
    redirect: '/dashboard/social',
    meta: {
      hiddenInMenu: true,
      moduleKey: 'portrait',
      requiresAuth: true,
    },
  }),
  buildModuleRoute({
    path: 'graph/collaboration',
    redirect: '/dashboard/social',
    meta: {
      hiddenInMenu: true,
      moduleKey: 'portrait',
      requiresAuth: true,
    },
  }),
  buildModuleRoute({
    path: 'graph/themes',
    redirect: '/dashboard/social',
    meta: {
      hiddenInMenu: true,
      moduleKey: 'portrait',
      requiresAuth: true,
    },
  }),
  buildModuleRoute({
    path: 'graph/explanation',
    redirect: '/dashboard/social',
    meta: {
      hiddenInMenu: true,
      moduleKey: 'portrait',
      requiresAuth: true,
    },
  }),
  buildModuleRoute({
    path: 'project-recommendations',
    component: RouterView,
    meta: {
      title: '项目推荐',
      icon: 'MagicStick',
      order: 50,
      moduleKey: 'recommendation',
      moduleRoot: true,
      requiresAuth: true,
      menuRoles: ['teacher'],
    },
    children: [
      {
        path: '',
        name: 'project-recommendations',
        component: ProjectRecommendationView,
        props: { sectionMode: 'results' },
        meta: {
          title: '推荐结果',
          order: 10,
          moduleKey: 'recommendation',
          requiresAuth: true,
        },
      },
      {
        path: 'feedback',
        name: 'project-recommendations-feedback',
        component: ProjectRecommendationView,
        props: { sectionMode: 'feedback' },
        meta: {
          title: '收藏与反馈',
          order: 20,
          moduleKey: 'recommendation',
          requiresAuth: true,
        },
      },
      {
        path: 'preparation',
        name: 'project-recommendations-preparation',
        component: ProjectRecommendationView,
        props: { sectionMode: 'preparation' },
        meta: {
          title: '申报准备',
          order: 30,
          moduleKey: 'recommendation',
          requiresAuth: true,
        },
      },
    ],
  }),
  buildModuleRoute({
    path: 'assistant-demo/:pathMatch(.*)*',
    redirect: '/dashboard',
    meta: {
      hiddenInMenu: true,
      moduleKey: 'assistant',
      requiresAuth: true,
    },
  }),
  buildModuleRoute({
    path: 'teachers',
    component: RouterView,
    meta: {
      title: '教师管理',
      icon: 'UserFilled',
      order: 110,
      moduleKey: 'teacher-management',
      moduleRoot: true,
      requiresAuth: true,
      requiresAdmin: true,
      menuRoles: ['admin', 'college_admin'],
    },
    children: [
      {
        path: '',
        name: 'teacher-management',
        component: TeacherManagementView,
        props: { sectionMode: 'overview' },
        meta: {
          title: '教师总览',
          order: 10,
          moduleKey: 'teacher-management',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['admin', 'college_admin'],
        },
      },
      {
        path: 'college-admins',
        name: 'teacher-management-college-admins',
        component: TeacherManagementView,
        props: { sectionMode: 'create-college-admin' },
        meta: {
          title: '创建学院管理员',
          order: 20,
          moduleKey: 'teacher-management',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['admin'],
        },
      },
      {
        path: 'accounts',
        name: 'teacher-management-accounts',
        component: TeacherManagementView,
        props: { sectionMode: 'create-teacher' },
        meta: {
          title: '创建教师账号',
          order: 20,
          moduleKey: 'teacher-management',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['college_admin'],
        },
      },
      {
        path: 'achievement-review',
        name: 'teacher-management-achievement-review',
        component: AchievementReviewView,
        meta: {
          title: '成果审核',
          order: 30,
          moduleKey: 'teacher-management',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['college_admin'],
        },
      },
    ],
  }),
  buildModuleRoute({
    path: 'academy-dashboard',
    component: RouterView,
    meta: {
      title: '学院看板',
      icon: 'DataAnalysis',
      order: 120,
      moduleKey: 'academy-dashboard',
      moduleRoot: true,
      requiresAuth: true,
      requiresAdmin: true,
      menuRoles: ['admin', 'college_admin'],
    },
    children: [
      {
        path: '',
        name: 'academy-dashboard',
        component: AcademyDashboardView,
        props: { sectionMode: 'overview' },
        meta: {
          title: '总览',
          order: 10,
          moduleKey: 'academy-dashboard',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['admin', 'college_admin'],
        },
      },
      {
        path: 'comparison',
        name: 'academy-dashboard-comparison',
        component: AcademyDashboardView,
        props: { sectionMode: 'comparison' },
        meta: {
          title: '学院对比',
          order: 20,
          moduleKey: 'academy-dashboard',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['admin'],
        },
      },
      {
        path: 'drilldown',
        name: 'academy-dashboard-drilldown',
        component: AcademyDashboardView,
        props: { sectionMode: 'drilldown' },
        meta: {
          title: '学院钻取',
          order: 30,
          moduleKey: 'academy-dashboard',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['admin'],
        },
      },
      {
        path: 'teacher-analysis',
        name: 'academy-dashboard-teacher-analysis',
        component: AcademyDashboardView,
        props: { sectionMode: 'teacher-analysis' },
        meta: {
          title: '教师分析',
          order: 20,
          moduleKey: 'academy-dashboard',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['college_admin'],
        },
      },
    ],
  }),
  buildModuleRoute({
    path: 'project-guides',
    component: RouterView,
    meta: {
      title: '项目指南管理',
      icon: 'Reading',
      order: 130,
      moduleKey: 'project-guide-management',
      moduleRoot: true,
      requiresAuth: true,
      requiresAdmin: true,
      menuRoles: ['admin', 'college_admin'],
    },
    children: [
      {
        path: '',
        name: 'project-guide-management',
        component: ProjectGuideManagementView,
        props: { sectionMode: 'overview' },
        meta: {
          title: '指南总览',
          order: 10,
          moduleKey: 'project-guide-management',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['admin', 'college_admin'],
        },
      },
      {
        path: 'manage',
        name: 'project-guide-management-manage',
        component: ProjectGuideManagementView,
        props: { sectionMode: 'manage' },
        meta: {
          title: '新增项目',
          order: 20,
          moduleKey: 'project-guide-management',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['admin', 'college_admin'],
        },
      },
      {
        path: 'lifecycle',
        name: 'project-guide-management-lifecycle',
        component: ProjectGuideManagementView,
        props: { sectionMode: 'lifecycle' },
        meta: {
          title: '生命周期管理',
          order: 30,
          moduleKey: 'project-guide-management',
          requiresAuth: true,
          requiresAdmin: true,
          menuRoles: ['admin', 'college_admin'],
        },
      },
    ],
  }),
]
