# Generated by Django 5.2.9 on 2026-03-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='论文标题')),
                ('publish_date', models.DateField(verbose_name='发表日期')),
                ('journal_name', models.CharField(max_length=200, verbose_name='发表期刊/会议名称')),
                ('external_authors', models.CharField(blank=True, help_text='逗号分隔', max_length=255, null=True, verbose_name='外部作者')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='摘要')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='提取的关键词')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='录入时间')),
            ],
            options={
                'verbose_name': '科研论文',
                'verbose_name_plural': '科研论文',
            },
        ),
    ]
