# Generated by Django 5.2.9 on 2026-03-08 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('discipline', models.CharField(blank=True, max_length=200, verbose_name='所属学科')),
            ],
        ),
        migrations.AlterModelOptions(
            name='paper',
            options={},
        ),
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='external_authors',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='publish_date',
        ),
        migrations.AddField(
            model_name='paper',
            name='citation_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paper',
            name='date_acquired',
            field=models.DateField(default='2024-01-01', verbose_name='发表/立项时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='doi',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_first_author',
            field=models.BooleanField(default=True, verbose_name='是否第一作者/通讯作者'),
        ),
        migrations.AddField(
            model_name='paper',
            name='journal_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='期刊等级（SCI/EI/CCF等）'),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_type',
            field=models.CharField(choices=[('JOURNAL', '期刊论文'), ('CONFERENCE', '会议论文')], default='2024-01-01', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paper',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='abstract',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paper',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='paper',
            name='title',
            field=models.CharField(max_length=300),
        ),
        migrations.CreateModel(
            name='AcademicService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_acquired', models.DateField(verbose_name='发表/立项时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_type', models.CharField(choices=[('EDITOR', '期刊编委'), ('REVIEWER', '期刊审稿'), ('COMMITTEE', '学术委员会'), ('INVITED_TALK', '特邀报告')], max_length=50)),
                ('organization', models.CharField(max_length=300, verbose_name='服务机构')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=300)),
                ('is_internal', models.BooleanField(default=False, verbose_name='是否本校教师')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coauthors', to='achievements.paper')),
            ],
        ),
        migrations.CreateModel(
            name='IntellectualProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_acquired', models.DateField(verbose_name='发表/立项时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_type', models.CharField(choices=[('PATENT_INVENTION', '发明专利'), ('PATENT_UTILITY', '实用新型'), ('SOFTWARE_COPYRIGHT', '软件著作权')], max_length=50)),
                ('registration_number', models.CharField(max_length=200)),
                ('is_transformed', models.BooleanField(default=False, verbose_name='是否成果转化')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_acquired', models.DateField(verbose_name='发表/立项时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('NATIONAL', '国家级'), ('PROVINCIAL', '省部级'), ('ENTERPRISE', '企业合作')], max_length=20)),
                ('role', models.CharField(choices=[('PI', '负责人'), ('CO_PI', '参与人')], max_length=20)),
                ('funding_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='经费金额(万元)')),
                ('status', models.CharField(default='ONGOING', max_length=50, verbose_name='项目状态')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaperKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.paper')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='achievements.researchkeyword')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, verbose_name='所属学院')),
                ('discipline', models.CharField(max_length=200, verbose_name='所属学科')),
                ('title', models.CharField(max_length=100, verbose_name='职称')),
                ('research_interests', models.TextField(blank=True, verbose_name='研究方向')),
                ('h_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachingAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date_acquired', models.DateField(verbose_name='发表/立项时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('achievement_type', models.CharField(choices=[('COMPETITION', '学生竞赛'), ('TEACHING_REFORM', '教改项目'), ('COURSE', '精品课程'), ('THESIS', '优秀论文指导')], max_length=50)),
                ('level', models.CharField(max_length=100, verbose_name='级别')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
