# Generated by Django 5.2.9 on 2026-03-15 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_researchkeyword_alter_paper_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coauthor',
            name='internal_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coauthor_links', to=settings.AUTH_USER_MODEL, verbose_name='关联内部教师账号'),
        ),
    ]
