# Generated by Django 5.2.9 on 2026-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0006_paperoperationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='journal_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='期刊等级（SCI/EI/CCF 等）'),
        ),
    ]
