# Generated by Django 5.2.9 on 2026-04-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0009_achievement_review_flow_and_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='intellectualproperty',
            name='role',
            field=models.CharField(choices=[('PI', '负责人'), ('CO_PI', '参与人')], default='PI', max_length=20, verbose_name='承担角色'),
        ),
        migrations.AddField(
            model_name='teachingachievement',
            name='role',
            field=models.CharField(choices=[('PI', '负责人'), ('CO_PI', '参与人')], default='PI', max_length=20, verbose_name='承担角色'),
        ),
    ]
