# Generated by Django 5.2.9 on 2026-04-06 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0010_intellectualproperty_role_teachingachievement_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', '待认领'), ('ACCEPTED', '已认领'), ('REJECTED', '已拒绝')], default='PENDING', max_length=20, verbose_name='认领状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='邀请时间')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='achievements.paper', verbose_name='关联成果')),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_achievement_claims', to=settings.AUTH_USER_MODEL, verbose_name='录入者')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_claims', to=settings.AUTH_USER_MODEL, verbose_name='被邀请认领教师')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='achievement_status_19b9d4_idx'), models.Index(fields=['target_user', 'status'], name='achievement_target__0857e5_idx')],
                'constraints': [models.UniqueConstraint(fields=('achievement', 'target_user'), name='uniq_claim_achievement_target')],
            },
        ),
    ]
