# Generated by Django 5.2.9 on 2026-04-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0011_achievementclaim'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementclaim',
            name='coauthor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='achievements.coauthor', verbose_name='关联合作者记录'),
        ),
        migrations.AddField(
            model_name='achievementclaim',
            name='confirmation_note',
            field=models.TextField(blank=True, verbose_name='认领备注'),
        ),
        migrations.AddField(
            model_name='achievementclaim',
            name='confirmed_author_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='确认位次'),
        ),
        migrations.AddField(
            model_name='achievementclaim',
            name='proposed_author_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='发起位次'),
        ),
        migrations.AddField(
            model_name='achievementclaim',
            name='rank_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='位次确认时间'),
        ),
        migrations.AddField(
            model_name='coauthor',
            name='author_rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='作者位次'),
        ),
    ]
