# Generated by Django 5.2.9 on 2026-04-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0012_achievementclaim_coauthor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementclaim',
            name='confirmed_is_corresponding',
            field=models.BooleanField(default=False, verbose_name='确认通讯作者标记'),
        ),
        migrations.AddField(
            model_name='achievementclaim',
            name='proposed_is_corresponding',
            field=models.BooleanField(default=False, verbose_name='发起通讯作者标记'),
        ),
        migrations.AddField(
            model_name='coauthor',
            name='is_corresponding',
            field=models.BooleanField(default=False, verbose_name='是否通讯作者'),
        ),
        migrations.AddField(
            model_name='paper',
            name='is_corresponding_author',
            field=models.BooleanField(default=False, verbose_name='是否通讯作者'),
        ),
        migrations.AlterField(
            model_name='achievementclaim',
            name='status',
            field=models.CharField(choices=[('PENDING', '待认领'), ('ACCEPTED', '已认领'), ('REJECTED', '已拒绝'), ('CONFLICT', '存在争议')], default='PENDING', max_length=20, verbose_name='认领状态'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='is_first_author',
            field=models.BooleanField(default=True, verbose_name='是否第一作者'),
        ),
    ]
