# Generated by Django 5.2.9 on 2026-04-07 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0013_achievementclaim_confirmed_is_corresponding_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PortraitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='快照年份')),
                ('dimension_scores', models.JSONField(default=dict, verbose_name='维度得分')),
                ('total_score', models.FloatField(default=0.0, verbose_name='综合得分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='教师账号')),
            ],
            options={
                'ordering': ('-year', '-id'),
                'indexes': [models.Index(fields=['user', 'year'], name='achievement_user_id_24216e_idx'), models.Index(fields=['year'], name='achievement_year_fd017b_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'year'), name='uniq_portrait_snapshot_user_year')],
            },
        ),
    ]
