# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0014_portraitsnapshot'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeachingAchievement',
        ),
        migrations.AlterField(
            model_name='achievementoperationlog',
            name='achievement_type',
            field=models.CharField(
                choices=[
                    ('papers', '论文成果'),
                    ('projects', '科研项目'),
                    ('intellectual-properties', '知识产权'),
                    ('academic-services', '学术服务'),
                ],
                max_length=40,
            ),
        ),
    ]
