# Generated by Django 5.2.9 on 2026-04-23 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0017_remove_teacherprofile_h_index'),
        ('evaluation_rules', '0003_alter_evaluationruleitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicservice',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='achievementoperationlog',
            name='achievement_type',
            field=models.CharField(choices=[('papers', '论文成果'), ('projects', '科研项目'), ('intellectual-properties', '知识产权'), ('academic-services', '学术服务'), ('rule-achievements', '规则化成果')], max_length=40),
        ),
        migrations.AlterField(
            model_name='intellectualproperty',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='journal_level',
            field=models.CharField(blank=True, max_length=50, verbose_name='期刊级别（SCI/EI/CCF 等）'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='审核状态'),
        ),
        migrations.CreateModel(
            name='RuleBasedAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='成果名称')),
                ('external_reference', models.CharField(blank=True, max_length=200, verbose_name='批文号/登记号/外部编号')),
                ('date_acquired', models.DateField(verbose_name='成果时间')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING_REVIEW', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='DRAFT', max_length=20, verbose_name='审核状态')),
                ('issuing_organization', models.CharField(blank=True, max_length=300, verbose_name='发文/授奖/出版/采纳单位')),
                ('publication_name', models.CharField(blank=True, max_length=300, verbose_name='期刊/出版社/平台名称')),
                ('role_text', models.CharField(blank=True, max_length=120, verbose_name='本人角色')),
                ('author_rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='作者/完成人排名')),
                ('is_corresponding_author', models.BooleanField(default=False, verbose_name='是否通讯作者')),
                ('is_representative', models.BooleanField(default=False, verbose_name='是否代表成果')),
                ('school_unit_order', models.CharField(blank=True, max_length=120, verbose_name='学校署名/依托顺位')),
                ('amount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='计分金额/数量')),
                ('amount_unit', models.CharField(blank=True, max_length=40, verbose_name='金额/数量单位')),
                ('keywords_text', models.CharField(blank=True, max_length=300, verbose_name='关键词')),
                ('coauthor_names', models.JSONField(blank=True, default=list, verbose_name='合作者名单')),
                ('team_identifier', models.CharField(blank=True, max_length=200, verbose_name='团队归并标识')),
                ('team_total_members', models.PositiveIntegerField(blank=True, null=True, verbose_name='团队总人数')),
                ('team_allocated_score', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='本人分配积分')),
                ('team_contribution_note', models.TextField(blank=True, verbose_name='团队贡献说明')),
                ('evidence_note', models.TextField(blank=True, verbose_name='佐证说明')),
                ('factual_payload', models.JSONField(blank=True, default=dict, verbose_name='扩展事实字段')),
                ('provisional_score', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='预估积分')),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='生效积分')),
                ('score_detail', models.JSONField(blank=True, default=dict, verbose_name='计分明细')),
                ('rule_code_snapshot', models.CharField(blank=True, max_length=80, verbose_name='规则编码快照')),
                ('rule_title_snapshot', models.CharField(blank=True, max_length=255, verbose_name='规则名称快照')),
                ('category_code_snapshot', models.CharField(blank=True, max_length=80, verbose_name='分类编码快照')),
                ('category_name_snapshot', models.CharField(blank=True, max_length=120, verbose_name='分类名称快照')),
                ('score_text_snapshot', models.CharField(blank=True, max_length=120, verbose_name='积分文本快照')),
                ('include_in_total_snapshot', models.BooleanField(default=True, verbose_name='总分快照')),
                ('include_in_radar_snapshot', models.BooleanField(default=True, verbose_name='雷达快照')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievement_records', to='evaluation_rules.evaluationrulecategory', verbose_name='规则分类')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_rule_based_achievements', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('rule_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievement_records', to='evaluation_rules.evaluationruleitem', verbose_name='规则条目')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rule_based_achievements', to=settings.AUTH_USER_MODEL, verbose_name='教师账号')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievement_records', to='evaluation_rules.evaluationruleversion', verbose_name='规则版本')),
            ],
            options={
                'verbose_name': '规则化成果',
                'verbose_name_plural': '规则化成果',
                'ordering': ('-date_acquired', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='RuleBasedAchievementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rule-achievements/%Y/%m/', verbose_name='佐证文件')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='achievements.rulebasedachievement', verbose_name='关联成果')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_rule_achievement_attachments', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '规则成果附件',
                'verbose_name_plural': '规则成果附件',
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='rulebasedachievement',
            index=models.Index(fields=['teacher', 'status'], name='achievement_teacher_886680_idx'),
        ),
        migrations.AddIndex(
            model_name='rulebasedachievement',
            index=models.Index(fields=['teacher', 'date_acquired'], name='achievement_teacher_d173a2_idx'),
        ),
        migrations.AddIndex(
            model_name='rulebasedachievement',
            index=models.Index(fields=['category', 'status'], name='achievement_categor_88de76_idx'),
        ),
        migrations.AddIndex(
            model_name='rulebasedachievement',
            index=models.Index(fields=['rule_item', 'status'], name='achievement_rule_it_8da23a_idx'),
        ),
        migrations.AddIndex(
            model_name='rulebasedachievement',
            index=models.Index(fields=['team_identifier'], name='achievement_team_id_ef365d_idx'),
        ),
    ]
