# Generated by Django 5.2.9 on 2026-04-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_guides', '0003_recommendation_records_and_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学院名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='projectguide',
            name='scope',
            field=models.CharField(choices=[('GLOBAL', '全局'), ('ACADEMY', '学院')], default='GLOBAL', max_length=20, verbose_name='发布范围'),
        ),
        migrations.AlterField(
            model_name='projectguide',
            name='status',
            field=models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '申报中'), ('URGENT', '临近截止'), ('ARCHIVED', '已结束')], default='DRAFT', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='projectguide',
            name='academy',
            field=models.ForeignKey(blank=True, db_column='academy_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_guides', to='project_guides.academy', verbose_name='归属学院'),
        ),
    ]
