# Generated by Django 5.2.9 on 2026-04-07 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_normalize_teacher_usernames'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PROJECT_GUIDE_PUSH', '项目指南推送'), ('ACHIEVEMENT_CLAIM', '成果认领邀请'), ('CLAIM_REMINDER', '成果认领提醒')], max_length=40, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='通知标题')),
                ('content', models.TextField(blank=True, verbose_name='通知内容')),
                ('action_path', models.CharField(blank=True, max_length=200, verbose_name='跳转路径')),
                ('action_query', models.JSONField(blank=True, default=dict, verbose_name='跳转参数')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='补充载荷')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='已读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name': '用户通知',
                'verbose_name_plural': '用户通知',
                'ordering': ('is_read', '-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='users_usern_recipie_54b44c_idx'), models.Index(fields=['category', 'created_at'], name='users_usern_categor_c5c6ef_idx')],
            },
        ),
    ]
