# Generated by Django 5.2.6 on 2026-04-21 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_usernotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeacherTitleChangeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("current_title", models.CharField(blank=True, default="", max_length=50, verbose_name="当前职称")),
                ("requested_title", models.CharField(max_length=50, verbose_name="申请职称")),
                ("apply_reason", models.CharField(blank=True, default="", max_length=300, verbose_name="申请说明")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审核"),
                            ("APPROVED", "已通过"),
                            ("REJECTED", "已驳回"),
                            ("CANCELED", "已撤回"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="审核状态",
                    ),
                ),
                ("review_comment", models.CharField(blank=True, default="", max_length=300, verbose_name="审核意见")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="申请时间")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True, verbose_name="审核时间")),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_title_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核人",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="title_change_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="申请教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师职称变更申请",
                "verbose_name_plural": "教师职称变更申请",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddIndex(
            model_name="teachertitlechangerequest",
            index=models.Index(fields=["teacher", "status"], name="users_teach_teacher_b8f38a_idx"),
        ),
        migrations.AddIndex(
            model_name="teachertitlechangerequest",
            index=models.Index(fields=["status", "created_at"], name="users_teach_status_844ddf_idx"),
        ),
    ]
