# Generated by Django 5.2.9 on 2026-04-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teachertitlechangerequest'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='teachertitlechangerequest',
            new_name='users_teach_teacher_c50757_idx',
            old_name='users_teach_teacher_b8f38a_idx',
        ),
        migrations.RenameIndex(
            model_name='teachertitlechangerequest',
            new_name='users_teach_status_24a102_idx',
            old_name='users_teach_status_844ddf_idx',
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='category',
            field=models.CharField(choices=[('PROJECT_GUIDE_PUSH', '项目指南推送'), ('ACHIEVEMENT_CLAIM', '成果认领邀请'), ('CLAIM_REMINDER', '成果认领提醒'), ('PASSWORD_RESET_REQUEST', '密码重置申请'), ('TITLE_CHANGE_REQUEST', '职称变更申请')], max_length=40, verbose_name='通知类型'),
        ),
    ]
