# Generated by Django 5.2.9 on 2026-04-29 13:25

from django.db import migrations


STANDARD_COLLEGES = [
    "文学院",
    "政法与公共管理学院",
    "历史文化学院",
    "鲁迅艺术学院",
    "经管学院",
    "体育学院",
    "外国语学院",
    "数学与计算机科学学院",
    "物理与电子信息学院",
    "化学与化工学院",
    "生命科学学院",
    "石油学院",
    "建筑工程学院",
    "教育科学学院",
    "马克思主义学院",
    "医学院",
    "继续教育学院",
]

COLLEGE_ALIASES = {
    "信息工程学院": "数学与计算机科学学院",
    "人工智能学院": "数学与计算机科学学院",
    "计算机学院": "数学与计算机科学学院",
    "软件学院": "数学与计算机科学学院",
    "数学与计算机学院": "数学与计算机科学学院",
    "数学计算机科学学院": "数学与计算机科学学院",
    "物电学院": "物理与电子信息学院",
    "物理学院": "物理与电子信息学院",
    "电子信息学院": "物理与电子信息学院",
    "政法学院": "政法与公共管理学院",
    "公共管理学院": "政法与公共管理学院",
    "教育学院": "教育科学学院",
    "教育技术学院": "教育科学学院",
    "经济管理学院": "经管学院",
    "经济与管理学院": "经管学院",
    "化工学院": "化学与化工学院",
    "化学学院": "化学与化工学院",
    "建筑学院": "建筑工程学院",
    "土木工程学院": "建筑工程学院",
}


def seed_standard_colleges(apps, schema_editor):
    College = apps.get_model("users", "College")
    CustomUser = apps.get_model("users", "CustomUser")

    for index, name in enumerate(STANDARD_COLLEGES, start=1):
        College.objects.update_or_create(
            name=name,
            defaults={
                "sort_order": index,
                "is_active": True,
            },
        )

    for old_name, new_name in COLLEGE_ALIASES.items():
        CustomUser.objects.filter(department=old_name).update(department=new_name)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_college'),
    ]

    operations = [
        migrations.RunPython(seed_standard_colleges, noop_reverse),
    ]
